FROM node:13-alpine as node-portal-bi-web-develop
RUN npm cache clean --force
RUN rm -rf node_modules package-lock.json
WORKDIR /app
COPY package.json /app
RUN npm install
COPY . .
RUN npm run prebuild
RUN npm run build

FROM nginx:alpine as nginx-portal-bi-web-develop
VOLUME /var/cache/nginx
COPY --from=node-portal-bi-web-develop app/build /usr/share/nginx/html
COPY ./nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
